<a href="https://colab.research.google.com/github/Merly2004/Examen-Final-Practico/blob/main/Examen_Final_Practico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import math

#================================
#PARTE 1: Fundamentos NumPy
#================================

In [83]:
# 1. Crea un arreglo NumPy de dimensión 1 con los números del 1 al 20.
arr = np.arange(1, 21)
print("Parte 1.1 - Arreglo del 1 al 20:")
print(arr)

Parte 1.1 - Arreglo del 1 al 20:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [84]:
# 2. Selecciona los múltiplos de 3 de ese arreglo y muéstralos.
multiplos_3 = arr[arr % 3 == 0]
print("Parte 1.2 - Múltiplos de 3:")
print(multiplos_3)

Parte 1.2 - Múltiplos de 3:
[ 3  6  9 12 15 18]


In [86]:
# 3. Genera una matriz aleatoria de tamaño 5x5 con números entre 0 y 1.
matriz = np.random.rand(5, 5)
print("Parte 1.3 - Matriz aleatoria 5x5:")
print(matriz)

Parte 1.3 - Matriz aleatoria 5x5:
[[0.36876258 0.65106497 0.25894119 0.81825098 0.95165351]
 [0.46979829 0.54292219 0.33538551 0.17981387 0.93106967]
 [0.88931762 0.58288268 0.05228386 0.3772295  0.27032162]
 [0.90974403 0.45564253 0.27836486 0.75043    0.09993464]
 [0.16456907 0.14248412 0.40499054 0.22015241 0.8721865 ]]


In [87]:
# 4. Calcula la media, la desviación estándar y el valor máximo de esa matriz.
media = np.mean(matriz)
desv = np.std(matriz)
maximo = np.max(matriz)
print("Parte 1.4 - Estadísticas:")
print(f"Media: {media}, Desviación Estándar: {desv}, Máximo: {maximo}")

Parte 1.4 - Estadísticas:
Media: 0.4791278700189129, Desviación Estándar: 0.28603389138189006, Máximo: 0.9516535128819147


In [88]:
# 5. Transforma la matriz en un vector de una sola dimensión.
vector = matriz.flatten()
print("Parte 1.5 - Matriz a vector:")
print(vector)

Parte 1.5 - Matriz a vector:
[0.36876258 0.65106497 0.25894119 0.81825098 0.95165351 0.46979829
 0.54292219 0.33538551 0.17981387 0.93106967 0.88931762 0.58288268
 0.05228386 0.3772295  0.27032162 0.90974403 0.45564253 0.27836486
 0.75043    0.09993464 0.16456907 0.14248412 0.40499054 0.22015241
 0.8721865 ]


# ================================
# PARTE 2: Fundamentos Pandas
# ================================

In [89]:
data = {
    "Nombre": ["Ana", "Luis", "María", "Pedro", "Sofía"],
    "Edad": [20, 21, 19, 22, 20],
    "Nota_Matemáticas": [18, 15, 16, 12, 19],
    "Nota_IA": [17, 14, 18, 13, 20]
}

df = pd.DataFrame(data)
print("Parte 2.1 - DataFrame inicial:\n")
print(df)

Parte 2.1 - DataFrame inicial:

  Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
1   Luis    21                15       14
2  María    19                16       18
3  Pedro    22                12       13
4  Sofía    20                19       20


In [90]:
# 2. Promedio de cada columna numérica
print("Parte 2.2 - Promedios:\n")
print(df.mean(numeric_only=True))

Parte 2.2 - Promedios:

Edad                20.4
Nota_Matemáticas    16.0
Nota_IA             16.4
dtype: float64


In [91]:
# 3. Filtrar estudiantes con Nota_IA > 15
print("Parte 2.3 - Estudiantes con Nota_IA > 15:\n")
print(df[df["Nota_IA"] > 15])

Parte 2.3 - Estudiantes con Nota_IA > 15:

  Nombre  Edad  Nota_Matemáticas  Nota_IA
0    Ana    20                18       17
2  María    19                16       18
4  Sofía    20                19       20


In [92]:
# 4. Nueva columna 'Promedio'
df["Promedio"] = df[["Nota_Matemáticas", "Nota_IA"]].mean(axis=1)
print("Parte 2.4 - DataFrame con Promedio:\n")
print(df)

Parte 2.4 - DataFrame con Promedio:

  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
0    Ana    20                18       17      17.5
1   Luis    21                15       14      14.5
2  María    19                16       18      17.0
3  Pedro    22                12       13      12.5
4  Sofía    20                19       20      19.5


In [94]:
# 5. Ordenar por Promedio
# Ensure that cell QM_SYOChh6Eu has been executed to create the 'Promedio' column in the DataFrame 'df'.
df_ordenado = df.sort_values(by="Promedio", ascending=False)
print("Parte 2.5 - DataFrame ordenado por Promedio:\n")
print(df_ordenado)

Parte 2.5 - DataFrame ordenado por Promedio:

  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio
4  Sofía    20                19       20      19.5
0    Ana    20                18       17      17.5
2  María    19                16       18      17.0
1   Luis    21                15       14      14.5
3  Pedro    22                12       13      12.5


# ================================
# PARTE 3: Algoritmia aplicada
# ================================

In [58]:
# 1. Función que recibe lista y devuelve mayor, menor y promedio
def resumen_lista(nums):
    return {
        "Mayor": max(nums),
        "Menor": min(nums),
        "Promedio": sum(nums)/len(nums)
    }

print("Parte 3.1 → Resumen de lista [4, 7, 1, 9, 3]:")
print(resumen_lista([4, 7, 1, 9, 3]))

Parte 3.1 → Resumen de lista [4, 7, 1, 9, 3]:
{'Mayor': 9, 'Menor': 1, 'Promedio': 4.8}


In [59]:
# 2. Función de activación Sigmoide
sig = lambda x: 1 / (1 + np.exp(-x))
entrada = np.array([-2, -1, 0, 1, 2])
print("Parte 3.2 → Sigmoide aplicada:")
print(sig(entrada))

Parte 3.2 → Sigmoide aplicada:
[0.11920292 0.26894142 0.5        0.73105858 0.88079708]


In [69]:
# 3. Clasificación Aprobado/Desaprobado
df["Estado"] = np.where(df["Promedio"] >= 14, "Aprobado", "Desaprobado")
print("\nParte 3.3 - DataFrame con Estado:")
print(df)


Parte 3.3 - DataFrame con Estado:
  Nombre  Edad  Nota_Matemáticas  Nota_IA  Promedio       Estado
0    Ana    20                18       17      17.5     Aprobado
1   Luis    21                15       14      14.5     Aprobado
2  María    19                16       18      17.0     Aprobado
3  Pedro    22                12       13      12.5  Desaprobado
4  Sofía    20                19       20      19.5     Aprobado


# ================================
# PARTE 4: Mini-proyecto
# ================================

In [15]:
# Dataset simulado de ventas
ventas = pd.DataFrame({
    "Producto": ["A", "B", "C", "D"],
    "Ventas_2024": [100, 150, 200, 250],
    "Ventas_2025": [120, 180, 240, 400]
})

In [95]:
# 1. Columna Crecimiento
ventas["Crecimiento"] = ((ventas["Ventas_2025"] - ventas["Ventas_2024"]) / ventas["Ventas_2024"]) * 100
print("Parte 4.1 - Dataset con Crecimiento:\n")
print(ventas)

Parte 4.1 - Dataset con Crecimiento:

  Producto  Ventas_2024  Ventas_2025  Crecimiento
0        A          100          120         20.0
1        B          150          180         20.0
2        C          200          240         20.0
3        D          250          400         60.0


In [96]:
# 2. Producto con mayor crecimiento
mayor_crecimiento = ventas.loc[ventas["Crecimiento"].idxmax()]
print("Parte 4.2 - Producto con mayor crecimiento:\n")
print(mayor_crecimiento)

Parte 4.2 - Producto con mayor crecimiento:

Producto          D
Ventas_2024     250
Ventas_2025     400
Crecimiento    60.0
Name: 3, dtype: object


# ================================
# PARTE 5: Resolución de ecuaciones
# ================================

In [101]:
# 1. Ecuación de primer grado ax + b = 0
def resolver_lineal(a, b):
    if a == 0:
        return "Sin solución" if b != 0 else "Infinitas soluciones"
    return -b / a

print("Parte 5.1 - Ecuación 2x + 4 = 0:")
print("Respuesta es:", resolver_lineal(2, 4))


Parte 5.1 - Ecuación 2x + 4 = 0:
Respuesta es: -2.0


In [100]:
# 2. Ecuación de segundo grado ax^2 + bx + c = 0
def resolver_cuadratica(a, b, c):
    discriminante = b**2 - 4*a*c
    if discriminante >= 0:
        x1 = (-b + math.sqrt(discriminante)) / (2*a)
        x2 = (-b - math.sqrt(discriminante)) / (2*a)
    else:
        # soluciones complejas
        real = -b / (2*a)
        imag = math.sqrt(-discriminante) / (2*a)
        x1 = complex(real, imag)
        x2 = complex(real, -imag)
    return x1, x2

print("\nParte 5.2 - Ecuación x^2 - 5x + 6 = 0:")
print("Respuesta es:", resolver_cuadratica(1, -5, 6))


Parte 5.2 - Ecuación x^2 - 5x + 6 = 0:
Respuesta es: (3.0, 2.0)
